### ISSUE TITLE
ActiveResource::ServerError : Failed. Response code = 500. Response message = Internal Server Error.

### ISSUE THREAD

**Issue by krainboltgreene** [Shopify/shopify_api#374]
```
vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/connection.rb:166:in `handle_response': Failed.  Response code = 500.  Response message = Internal Server Error. (ActiveResource::ServerError)
    from vendor/bundle/ruby/2.2.0/gems/shopify_api-4.3.7/lib/shopify_api/connection.rb:7:in `handle_response'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/connection.rb:133:in `request'
    from vendor/bundle/ruby/2.2.0/gems/shopify_api-4.3.7/lib/shopify_api/connection.rb:15:in `request'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/connection.rb:116:in `block in post'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/connection.rb:227:in `with_auth'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/connection.rb:116:in `post'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:1496:in `block in create'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:1495:in `create'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:1285:in `block in save'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:1284:in `save'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/validations.rb:117:in `save_with_validation'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:1303:in `save!'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:867:in `block in create!'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:867:in `tap'
    from vendor/bundle/ruby/2.2.0/bundler/gems/activeresource-e28f907145c3/lib/active_resource/base.rb:867:in `create!'
```

**Comment by ShayneP** [comment]
Sorry about the late response, but I figured I'd respond for posterity.

Looking at the logs, you're getting a timeout where your theme was hosted.
