### ISSUE TITLE
Orders with refunds containing discounts starting with integers will throw a "wrong constant name" exception

### ISSUE THREAD

**Issue by ashleyfulks** [Shopify/shopify_api#437]
### Problem

When an order has a refund that includes a discount code starting with an integer, any attempts to retrieve that error will throw the 'wrong constant name' exception.

### Scope

Any store using the API resource "refunds"

### Examples

Here's a sample refunds hash returned for an order (with some fields removed)

```
{
  "refunds": [
          {
                "id": 20714848300,
                "transactions": [
                    {
                        "receipt": {
                            "card_transaction": {
                                "status": "paid",
                                "amount": "98.87",
                                "currency": "NZD"
                            },
                            "card_details": {
                                "type": "Visa"
                            },
                            "discount_details": {
                                "2FOR99": {
                                    "code": "2FOR99",
                                    "amount": "32.00"
                                }
                            }
                        },
                    }
                ]
          }
      ]
}
```

Activeresource will try and find_or_create the resource for "2FOR99", which is not a valid constant and an exception is thrown.

Stack Trace:

```
NameError: wrong constant name 2FOR99
  from active_resource/base.rb:1571:in `const_defined?'
  from active_resource/base.rb:1571:in `find_or_create_resource_for'
  from active_resource/base.rb:1415:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1416:in `new'
  from active_resource/base.rb:1416:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1416:in `new'
  from active_resource/base.rb:1416:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1409:in `new'
  from active_resource/base.rb:1409:in `block (2 levels) in load'
  from active_resource/base.rb:1406:in `map'
  from active_resource/base.rb:1406:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1062:in `new'
  from active_resource/base.rb:1062:in `instantiate_record'
  from active_resource/base.rb:1058:in `block in instantiate_collection'
  from active_resource/collection.rb:68:in `block in collect!'
  from active_resource/collection.rb:8:in `each'
  from active_resource/collection.rb:8:in `each'
  from active_resource/collection.rb:68:in `collect!'
  from active_resource/base.rb:1058:in `instantiate_collection'
  from active_resource/base.rb:1027:in `find_every'
  from active_resource/base.rb:934:in `find'
```

### Expected Vs Actual

Expected: refund would be processed without error
Actual: refund throws exception

### Replication Steps

Create a refund API call on an order with a discount code

### More Information

Developer provided a Github issue of their own from this error and I copied their text: https://github.com/Shopify/shopify_api/issues/436
	
https://shopify.zendesk.com/agent/tickets/9182733
	
@Shopify/api 
@Shopify/core-orders-eng

**Comment by jtgrenz** [comment]
Closing this as a duplicate. This is more or less a copy/paste of another linked issue 🤷‍♂️
