### ISSUE TITLE
Error 500 occurring sporadically in omniauth session callback

### ISSUE THREAD

**Issue by kidush** [Shopify/shopify_api#450]
Hey guys, I'm getting this error 500 sporadically and I dunno why just few users are facing this error
Do you guys have any ideas?
```
ActiveResource::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.
  from active_resource/connection.rb:166:in `handle_response'
  from config/initializers/shopify_api.rb:36:in `handle_response'
  from active_resource/connection.rb:133:in `request'
  from shopify_api/connection.rb:15:in `request'
  from active_resource/connection.rb:92:in `block in get'
  from active_resource/connection.rb:227:in `with_auth'
  from active_resource/connection.rb:92:in `get'
  from active_resource/base.rb:1043:in `find_one'
  from active_resource/base.rb:937:in `find'
  from shopify_api/resources/shop.rb:6:in `current'
  from app/services/shopifys/oauth_find_or_register.rb:30:in `block in call'
  from app/models/integrated_store.rb:109:in `block in open_session'
  from shopify_api/session.rb:30:in `temp'
  from app/models/integrated_store.rb:108:in `open_session'
  from app/services/shopifys/oauth_find_or_register.rb:30:in `call'
  from app/controllers/dropshippers/omniauth_callbacks_controller.rb:8:in `shopify'
  from action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:186:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:108:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:117:in `instance_exec'
  from active_support/callbacks.rb:117:in `block in run_callbacks'
  from active_support/callbacks.rb:135:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:20:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:166:in `block in instrument'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_support/notifications.rb:166:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:252:in `process_action'
  from searchkick/logging.rb:209:in `process_action'
  from active_record/railties/controller_runtime.rb:22:in `process_action'
  from abstract_controller/base.rb:124:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:189:in `dispatch'
  from action_controller/metal.rb:253:in `dispatch'
  from action_dispatch/routing/route_set.rb:49:in `dispatch'
  from action_dispatch/routing/route_set.rb:31:in `serve'
  from action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
  from action_dispatch/routing/mapper.rb:46:in `serve'
  from action_dispatch/journey/router.rb:50:in `block in serve'
  from action_dispatch/journey/router.rb:33:in `each'
  from action_dispatch/journey/router.rb:33:in `serve'
  from action_dispatch/routing/route_set.rb:834:in `call'
  from rack/pjax.rb:12:in `call'
  from omniauth/strategy.rb:415:in `call_app!'
  from omniauth/strategy.rb:369:in `callback_phase'
  from omniauth/strategies/oauth2.rb:75:in `callback_phase'
  from omniauth/strategies/shopify.rb:121:in `callback_phase'
  from omniauth/strategy.rb:236:in `callback_call'
  from omniauth/strategy.rb:188:in `call!'
  from omniauth/strategy.rb:168:in `call'
  from rack/method_override.rb:22:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from rack/attack.rb:147:in `call'
  from remotipart/middleware.rb:32:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:35:in `catch'
  from warden/manager.rb:35:in `call'
  from rack/etag.rb:25:in `call'
  from rack/conditional_get.rb:25:in `call'
  from rack/head.rb:12:in `call'
  from action_dispatch/middleware/callbacks.rb:26:in `block in call'
  from active_support/callbacks.rb:97:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:24:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from rails/rack/logger.rb:36:in `call_app'
  from rails/rack/logger.rb:24:in `block in call'
  from active_support/tagged_logging.rb:69:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:69:in `tagged'
  from rails/rack/logger.rb:24:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from request_store/middleware.rb:19:in `call'
  from action_dispatch/middleware/request_id.rb:25:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from rack/sendfile.rb:111:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from rack/cors.rb:97:in `call'
  from rails/engine.rb:522:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:624:in `handle_request'
  from puma/server.rb:438:in `process_client'
  from puma/server.rb:302:in `block in run'
  from puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by 0ptimusrhyme** [comment]
Closing since I don't believe this has anything to do with the gem. That said, could you drop your request-id in here? I can have a look at our logging provided it happened recently enough. Request IDs are provided in response headers.
