### ISSUE TITLE
414 - URI Too Long

### ISSUE THREAD

**Issue by AnatolZaitsev** [Shopify/shopify_api#455]
I need to change products order in collection every day. So, I try to use [order for SmartCollection](https://help.shopify.com/api/reference/products/smartcollection#order) and it work for collections with 100+- products, but atst fails for collection with 500+ products.

```
ActiveResource::ClientError: Failed.  Response code = 414.  Response message = URI Too Long.
        from app/jobs/collections/shuffle_job.rb:15:in `block in perform'
        from app/jobs/collections/shuffle_job.rb:9:in `perform'
        from (irb):5
```

I think this error caused by PUT request limitations or maybe server configuration.

**Comment by mryurii** [comment]
It looks like restriction from shopify api to order only up to 250 products in SmartCollection.

> An array of product IDs, in the order that you want them to appear at the top of the collection. As of 2019, it will be possible to order a subset of products manually for collections with any sort order (limited to the first 250 products in a collection). When products is specified but empty, any previously sorted products are cleared.
https://help.shopify.com/en/api/reference/products/smartcollection#order-2019-07

@AnatolZaitsev Have you found some workaround for it?)

**Comment by AnatolZaitsev** [comment]
@mryurii Yep, I have to fetch collection several times:
```
APPLICABLE_COUNT = ((2000 / 14 / 100)*100).freeze
# 2000 - PUT-request's limit
# 14 - length of (product_id - 12, space - 1, comma character - 1)
# (n / 100)*100 - round to hundreds for integer count of iterations

collection = ShopifyAPI::SmartCollection.find(id)
fetch_service = FetchResourcesService.new(ShopifyAPI::Collect)
products_ids = fetch_service.get_all({ key: 'collection_id', value: id }, :product_id)
iterations = products_ids.count / APPLICABLE_COUNT

if iterations > 0
  i = 0
  while i <= iterations do
    collection.order(products: products_ids.shuffle.first(APPLICABLE_COUNT))
     i += 1
  end
else
  collection.order(products: products_ids.shuffle)
end
```
And this is my custom data fetcher from ShopifyAPI, which avoids hard limit for one query(250 items):
```
class FetchResourcesService

  DEFAULT_LIMIT_COUNT = 250.0.freeze

  def initialize(resource_class)
    @class = resource_class
    count = @class.count
    @pages = (count / DEFAULT_LIMIT_COUNT).ceil
    @limit = @pages == 1 ? count : DEFAULT_LIMIT_COUNT.to_i
  end

  def get_all(query_params = nil, target = nil)
    result = []

    1.upto(@pages) do |page|
      resources = @class.find(:all, params: { limit: @limit, page: page })

      if query_params && query_params[:key] && query_params[:value]
        condition = query_params[:condition] ? query_params[:condition] : nil

        case condition
          when 'greater_than'
            resources = resources.select { |res| res.send(query_params[:key]) > query_params[:value] }
          when 'less_than'
            resources = resources.select { |res| res.send(query_params[:key]) < query_params[:value] }
          when 'not_equals'
            resources = resources.select { |res| res.send(query_params[:key]) != query_params[:value] }
          when 'contains'
            resources = resources.select { |res| res.send(query_params[:key]).downcase.include?(query_params[:value]) }
          else
            resources = resources.select { |res| res.send(query_params[:key]) == query_params[:value] }
        end
      end

      resources = resources.map(&target) if target && resources.count > 0
      resources.each { |r| result << r }
    end

    result
  end
end
```
