### ISSUE TITLE
OpenSSL / ActiveResource SSL error

### ISSUE THREAD

**Issue by jamierumbelow** [Shopify/shopify_api#481]
After an upgrade (from 4.9.0 to 4.13.0) I'm having trouble getting the gem to make requests.

Example code:

```
begin
  ShopifyAPI::Base.activate_session(ShopifyAPI::Session.new(record[:domain], record[:token]))
  product = ShopifyAPI::Product.find(record[:external_product_id])
rescue ActiveResource::ResourceNotFound
  product = OpenStruct.new
end
```

I'm receiving the following error:

```
ActiveResource::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
app/services/results/csv/shops.rb:18:in `block in rows'
app/services/results/csv/shops.rb:15:in `each'
app/services/results/csv/shops.rb:15:in `map'
app/services/results/csv/shops.rb:15:in `rows'
app/services/results/csv/shops.rb:6:in `block in initialize'
app/services/results/csv/shops.rb:4:in `initialize'
app/services/results/create_export.rb:30:in `new'
app/services/results/create_export.rb:30:in `spreadsheets'
app/services/results/create_export.rb:14:in `upload_spreadsheets'
app/services/results/create_export.rb:6:in `initialize'
lib/tasks/results.rake:3:in `new'
lib/tasks/results.rake:3:in `block (2 levels) in <top (required)>'
/Users/jamierumbelow/.rbenv/versions/2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jamierumbelow/.rbenv/versions/2.5.0/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
```

I've tried downgrading the gem to the original version, and that doesn't seem to have worked. I've tried reinstalling OpenSSL, reinstalling Ruby (using rvm and rbenv in turn), I've tried regenerating my own self-signed SSL certificate (which shouldn't have anything to do with it, right? and which I also can't get Chrome to respect, regardless of how hard I try.) I've scrapped every gem and reinstalled the whole environment anew. And I've worked through these options: https://mislav.net/2013/07/ruby-openssl/.

I'm getting bored now. At this point, I'd like to just turn the damn thing off so I can get on with my life, but because ShopifyAPI manages its own ActiveResource connection, I'm not even sure how I can tell Net::HTTP to not verify (I've tried the constant override thing, and that didn't work).

I'd really appreciate any help you can give me.

**Comment by jamierumbelow** [comment]
After pushing the code to staging to test in a different environment, I'm getting a different error –

```
Errno::ECONNREFUSED: Failed to open TCP connection to :443 (Connection refused - connect(2) for nil port 443)
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:131:in `block in request'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:128:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/shopify_api-4.13.0/lib/shopify_api/connection.rb:15:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:92:in `block in get'
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:227:in `with_auth'
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:92:in `get'
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/base.rb:1051:in `find_single'
/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/base.rb:938:in `find'
/app/app/services/results/csv/shops.rb:18:in `block in rows'
/app/app/services/results/csv/shops.rb:15:in `each'
/app/app/services/results/csv/shops.rb:15:in `map'
/app/app/services/results/csv/shops.rb:15:in `rows'
/app/app/services/results/csv/shops.rb:6:in `block in initialize'
/app/app/services/results/csv/shops.rb:4:in `initialize'
/app/app/services/results/create_export.rb:30:in `new'
/app/app/services/results/create_export.rb:30:in `spreadsheets'
/app/app/services/results/create_export.rb:14:in `upload_spreadsheets'
/app/app/services/results/create_export.rb:6:in `initialize'
/app/lib/tasks/results.rake:3:in `new'
/app/lib/tasks/results.rake:3:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:104:in `load'
/app/bin/bundle:104:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 443
```

**Comment by jpriollaud** [comment]
+1

**Comment by jpriollaud** [comment]
Turns out the error is completely misleading the developer.  The problem has nothing to do with SSL certs.  Triple check your domain formation.  yourname.myshopify.com/admin or yourname.myshopify.com

**Comment by 0x962** [comment]
😢  Spent so much time on this issue, turns out it was a typo. Thanks for the comment!
