### ISSUE TITLE
oauth - can't post to shopify

### ISSUE THREAD

**Issue by smcalilly** [Shopify/shopify_api#619]
I'm trying to setup OAuth for a public app, but my request gets lost within the `request_token` method. The request comes in from Shopify and includes the `code` that my app is supposed to POST to Shopify in exchange for the `access_token`, but the `request_token` method doesn't process Shopify's request. It just sort of dies and doesn't throw any errors. My ShopifyAPI::Session instances are different across the two actions, "install" and "auth". I'm not sure how to get the class instance to persist across sessions. I've tried calling `ShopifyAPI::Session.request_token(params)` but get `undefined method request_token for ShopifyAPI::Session:Class`. I've also tried to use the Rails session storage to pass the `@shopify_session` across actions, but it changes the object to a hash and thus can't access the `ShopifyAPI::Session` class. I'm new to Rails, so apologies if this is painfully obvious and not an issue with the gem.

Controller:
```
class ShopifyController < ApplicationController
  before_action :shopify_session, only: [:install]

  def install
    scope = ["write_products"]

    logger.debug @shopify_session

    permission_url = @shopify_session.create_permission_url(scope, "https://#{APP_URL}/shopify/auth")

    redirect_to permission_url
  end

  def auth
    logger.debug shopify_session
    logger.debug request.params

    token = @shopify_session.request_token(request.params)
  end

  def shopify_session
    ShopifyAPI::Session.setup(api_key: ENV['SHOPIFY_PUBLIC_KEY'], secret: ENV['SHOPIFY_SECRET_KEY'])

    shop = request.params['shop']
    @shopify_session = ShopifyAPI::Session.new(domain: "#{shop}", api_version: "2019-07", token: nil)
  end
end
```

Logs:
```Started GET "/shopify/install?hmac=594fb2a8de76b3880e71d290c67df7af26bf774565bcd20da55626350a00d3ae&shop=sylvias-scarves.myshopify.com&timestamp=1567847968" for 108.248.50.187 at 2019-09-07 04:19:29 -0500
Cannot render console from 108.248.50.187! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
   (2.1ms)  SELECT sqlite_version(*)
   (1.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by ShopifyController#install as HTML
  Parameters: {"hmac"=>"594fb2a8de76b3880e71d290c67df7af26bf774565bcd20da55626350a00d3ae", "shop"=>"sylvias-scarves.myshopify.com", "timestamp"=>"1567847968"}
  User Load (2.8ms)  SELECT "users".* FROM "users" WHERE "users"."remember_token" = ? ORDER BY "users"."id" ASC LIMIT ?  [["remember_token", "{token}"], ["LIMIT", 1]]
  Account Load (1.6ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."user_id" = ? LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:18:in `require_account'
#<ShopifyAPI::Session:0x00007fd3fb9bac68>
#<ShopifyAPI::Session:0x00007fd3fb9bac68>
https://sylvias-scarves.myshopify.com/admin/oauth/authorize?client_id={clientid}&scope=write_products&redirect_uri=https://ca2c7843.ngrok.io/shopify/auth
Redirected to https://sylvias-scarves.myshopify.com/admin/oauth/authorize?client_id={clientid}&scope=write_products&redirect_uri=https://ca2c7843.ngrok.io/shopify/auth
Completed 302 Found in 57ms (ActiveRecord: 6.5ms | Allocations: 15565)

Started GET "/shopify/auth?code=541b7af37cd87364aef53058e2954d82&hmac=6b9ce8634cdaac23022559642034f31a05399e7284aaf1b18dd3456914ee57ae&shop=sylvias-scarves.myshopify.com&timestamp=1567847970" for 108.248.50.187 at 2019-09-07 04:19:30 -0500
Cannot render console from 108.248.50.187! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by ShopifyController#auth as HTML
  Parameters: {"code"=>"541b7af37cd87364aef53058e2954d82", "hmac"=>"6b9ce8634cdaac23022559642034f31a05399e7284aaf1b18dd3456914ee57ae", "shop"=>"sylvias-scarves.myshopify.com", "timestamp"=>"1567847970"}
  User Load (1.5ms)  SELECT "users".* FROM "users" WHERE "users"."remember_token" = ? ORDER BY "users"."id" ASC LIMIT ?  [["remember_token", "d0f760bb52e7644af90ee3a6cb2188fcfe5ef209"], ["LIMIT", 1]]
  Account Load (0.2ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."user_id" = ? LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:18:in `require_account'
#<ShopifyAPI::Session:0x00007fd3f7b5cf20>
true
{"code"=>"541b7af37cd87364aef53058e2954d82", "hmac"=>"6b9ce8634cdaac23022559642034f31a05399e7284aaf1b18dd3456914ee57ae", "shop"=>"sylvias-scarves.myshopify.com", "timestamp"=>"1567847970", "controller"=>"shopify", "action"=>"auth"}
  Rendering shopify/auth.html.erb within layouts/application
  Rendered shopify/auth.html.erb within layouts/application (Duration: 4.2ms | Allocations: 198)
  Rendered layouts/shared/_html_meta.html.erb (Duration: 1533.6ms | Allocations: 337766)
  Rendered layouts/shared/_brand.html.erb (Duration: 3.2ms | Allocations: 156)
  Rendered layouts/app/_header.html.erb (Duration: 9.8ms | Allocations: 794)
  Rendered layouts/shared/_flash.html.erb (Duration: 2.0ms | Allocations: 190)
  Rendered layouts/shared/_credits.html.erb (Duration: 3.5ms | Allocations: 158)
  Rendered layouts/app/_footer.html.erb (Duration: 6.5ms | Allocations: 485)
  Rendered layouts/app/_sidebar.html.erb (Duration: 2.8ms | Allocations: 767)
Completed 200 OK in 2073ms (Views: 1579.4ms | ActiveRecord: 1.7ms | Allocations: 347950)```

**Comment by smcalilly** [comment]
Ok, so my lack of Rails knowledge was causing the problem. Turns out that I've been stuck on this for a month and a half (in my free time), and it's been working the entire time. I was looking in my server logs and the network requests via my browser dev tools, expecting to find my app POST to Shopify. However, that POST is an outbound HTTP request and Rails only logs inbound requests. Additionally, the client's browser doesn't process that request, because the request is in the background, server-to-server (correct me if I'm wrong?). 

I realized this by adding `puts token` after `token = @shopify_session.request_token(request.params)`, and discovered that I'm receiving the tokens. I should've done that at the very beginning -- a careless mishap. I added a gem called http_logger, which logs any outbound HTTP requests. If anybody is reading this and knows a better way to access the outbound HTTP requests within a Rails controller, please let me know! Thanks
