### ISSUE TITLE
Cursor based pagination - URI::InvalidComponentError (bad component(expected absolute path component)

### ISSUE THREAD

**Issue by ristooi** [Shopify/shopify_api#713]
Recently I migrated my Shopify App to use Cursor based pagination and everything was smooth.
A few days ago I also started to use `elastic-apm` gem and things broke down.

```
prods = ShopifyAPI::Product.find(:all, params: {limit: 5})
GET https://myshop.myshopify.com:443/admin/api/2020-01/products.json?limit=5
```
All good.

```
prods.fetch_next_page
GET https://myshop.myshopify.com:443https://myshop.myshopify.com/admin/api/2020-01/products.json?limit=50&page_info=eyJkaXJlY3Rpb24iOiJuZXh0IiwibGFzdF9pZCI6MjA3MDE5MjE2MDgzMywibGFzdF92YWx1ZSI6IlByaW1lIHRpbWUifQ
```
Apparently `shopify_api` corrupts the request URL (namely PATH+QUERY part) and `elastic-apm` fails to validate it (using `URI::HTTPS.build`), causing:
`URI::InvalidComponentError (bad component(expected absolute path component):  https://myshop.myshopify.com/admin/api/2020-01/products.json`

I'm a bit astonished that the pagination itself worked with this corrupted URL. Note that first query is valid, but subsequent `fetch_next_page` corrupts it (but API still returns data correctly).

I fixed the URL quick & dirty with a middleware.

shopify_api (9.0.4)
shopify_app (12.0.7)
rails (6.0.2.2)
ruby "~> 2.6.5"

**Comment by tanema** [comment]
Can you check `prods.next_page_info` shopify_api does not do much to that URL other than extract it from the paging headers so I am not sure how this could happen.

**Comment by ristooi** [comment]
Looking at the Link headers they look valid:

```
prods = ShopifyAPI::Product.find(:all, params: {limit: 5})
:link=>["<https://myshop.myshopify.com/admin/api/2020-01/products.json?limit=5&page_info=eyJsYXN0X2lkIjo0NDc1NzE3ODEyMjcxLCJsYXN0X3ZhbHVlIjoiM00gODcxMEUgS3VwdW1haW5lbiBoaXVra2Fzcy5GRlAxIiwiZGlyZWN0aW9uIjoibmV4dCJ9>; rel=\"next\""]
```

```
prods.fetch_next_page
:link=>["<https://myshop.myshopify.com/admin/api/2020-01/products.json?limit=5&page_info=eyJkaXJlY3Rpb24iOiJwcmV2IiwibGFzdF9pZCI6NDQ3NTcwMDI0ODYyMywibGFzdF92YWx1ZSI6IjNNIENsZWFyRWFyIGtvcnZhdHVscHBhIn0>; rel=\"previous\", <https://myshop.myshopify.com/admin/api/2020-01/products.json?limit=5&page_info=eyJkaXJlY3Rpb24iOiJuZXh0IiwibGFzdF9pZCI6NDQ3NTI4ODgxMzYxNSwibGFzdF92YWx1ZSI6IjNNIEtpbmQgUmVtb3ZhbCBTaWxpa29uaXRlaXBwaSAyLDVjbXg1bSJ9>; rel=\"next\""]
```

Debugging a bit reveals:

```
URI::InvalidComponentError (bad component(expected absolute path component): https://myshop.myshopify.com/admin/api/2020-01/products.json
from elastic_apm/spies/net_http.rb:51:in `request'
from net/http.rb:1228:in `get'
from active_resource/connection.rb:124:in `block in request'
from active_support/notifications.rb:180:in `block in instrument'
from active_support/notifications/instrumenter.rb:24:in `instrument'
from active_support/notifications.rb:180:in `instrument'
from active_resource/connection.rb:121:in `request'
from shopify_api/connection.rb:15:in `request'
from active_resource/connection.rb:85:in `block in get'
from active_resource/connection.rb:220:in `with_auth'
from active_resource/connection.rb:85:in `get'
from active_resource/base.rb:1069:in `find_every' <--- sets :from to PATH (full URL)
from active_resource/base.rb:974:in `find'
from active_resource/base.rb:1006:in `all' <--- params [:all, {:from=>"https://myshop.myshopify.com/admin/api/2020-01/products.json?limit=5&page_info=eyJsYXN0X2lkIjo0NDc1NzE3ODEyMjcxLCJsYXN0X3ZhbHVlIjoiM00gODcxMEUgS3VwdW1haW5lbiBoaXVra2Fzcy5GRlAxIiwiZGlyZWN0aW9uIjoibmV4dCJ9"}]
from shopify_api/paginated_collection.rb:47:in `fetch_page'
from shopify_api/paginated_collection.rb:23:in `fetch_next_page'
```

**Comment by forsbergplustwo** [comment]
Unfortunately I'm seeing the same thing in my apps (started in the past weeks), mainly on the products resource:

Initial request is fine, but then:
```ruby
products.fetch_next_page
```

Results in:

```
 HTTP GET (81117.58ms)   https://myshop.myshopify.com:443https://myshop.myshopify.com/admin/api/2020-04/products.json?limit=250&page_info=eyJsYXN0X2lkIjo4Njc2OTM0MDg3LCJsYXN0X3ZhbHVlIjoiQXdlc29tZSBWVyBCYXkgUGFuZWwgVmFuIFN0aWNrZXIiLCJkaXJlY3Rpb24iOiJuZXh0In0
```
After **81 seconds** (!?) the Shopify REST API returns:
```
ActiveResource::ServerError (Failed.  Response code = 502.  Response message = Bad Gateway.)
```
I've gone through the shopify_api code but I've got no idea where to correct the issue :(

```
shopify_api (9.1.0)
ruby "~> 2.6.5"
Tested with Shopify Api Version: "2020-01" & "2020-04"
```
