### ISSUE TITLE
Cannot start Rails app after GraphQL schema dump

### ISSUE THREAD

**Issue by meltingice** [Shopify/shopify_api#774]
After following the GraphQL schema dump directions exactly, I am getting an error when attempting to start my Rails app. Commands run (with sensitive info removed):

```
$ foreman run rails shopify_api:graphql:dump SHOP_URL="https://API_KEY:API_SECRET@MYSHOP.myshopify.com" API_VERSION=2020-07
Fetching schema for 2020-07 API version...
Wrote file /path/to/project/db/shopify_graphql_schemas/2020-07.json

$ foreman run rails c
Traceback (most recent call last):
bin/rails: wrong constant name deliveryProfileCreatePayload (NameError)
```

If I delete all of the delivery profile related queries from the schema, I can get it to load, so the issue seems to be isolated to those specific queries.

I am running Rails 5.2.3, Ruby 2.6.6, and shopify_api 9.2.0.

**Comment by andyw8** [comment]
Hi @meltingice 

Would it possible to post full stack trace to help us understand where this error is originating?

**Comment by meltingice** [comment]
Sure, was able to get one by loading a fresh pry session and setting up the library manually.

```
[2] pry(main)> ShopifyAPI::Base.api_version = "2020-04"
[3] pry(main)> ShopifyAPI::GraphQL.schema_location = './db/shopify_graphql_schemas/'
[4] pry(main)> ShopifyAPI::GraphQL.initialize_clients

Exception: NameError: wrong constant name deliveryProfileCreatePayload
--
0: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/graphql-client-0.12.1/lib/graphql/client/schema.rb:51:in `const_set'
1: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/graphql-client-0.12.1/lib/graphql/client/schema.rb:51:in `block in generate'
2: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/graphql-client-0.12.1/lib/graphql/client/schema.rb:47:in `each'
3: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/graphql-client-0.12.1/lib/graphql/client/schema.rb:47:in `generate'
4: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/graphql-client-0.12.1/lib/graphql/client.rb:95:in `initialize'
5: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/shopify_api-9.2.0/lib/shopify_api/graphql.rb:62:in `new'
6: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/shopify_api-9.2.0/lib/shopify_api/graphql.rb:62:in `block in initialize_clients'
7: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/shopify_api-9.2.0/lib/shopify_api/graphql.rb:47:in `each'
8: /Users/ryanlefevre/.rvm/gems/ruby-2.6.6/gems/shopify_api-9.2.0/lib/shopify_api/graphql.rb:47:in `initialize_clients'
```
