### ISSUE TITLE
Error in rake task for graphQL client in Ruby app: "rake aborted! Don't know how to build task"

### ISSUE THREAD

**Issue by pupasam** [Shopify/shopify_api#856]
# Issue summary

I am a newbie to Ruby, so perhaps the fix is deadly simple. I am building a private Shopify app for my company which requires graphQL calls to the Admin API.

I am following this documentation (https://github.com/Shopify/shopify_api/blob/master/docs/graphql.md) to set up a graphQL client for the app. As per the documentation, I have made a Rakefile called Rakefile, as well as a shopify_graphql_schemas folder, in my root project folder. 

When I run the private app rake command (with my api_key, password, and shop name, and current API version), I run into an error.

## Expected behavior

When I run the private app rake command from the command line, a file called 2021-04.json should be created in /shopify_graphql_schemas, and I should be able to use the graphQL client to query the Admin API.

## Actual behavior

I get the following error message, with trace:

rake aborted!
Don't know how to build task 'shopify_api:graphql:dump' (See the list of available tasks with `rake --tasks`)
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task_manager.rb:59:in `[]'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:159:in `invoke_task'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
C:/Ruby27-x64/bin/rake:23:in `load'
C:/Ruby27-x64/bin/rake:23:in `<main>'

## Steps to reproduce the problem

1. create a project folder with a simple app.rb which requires shopify_api and rake
2. add a Rakefile and a folder called shopify_graphql_schemas
3. from the command line, run:
rake shopify_api:graphql:dump SHOP_URL="https://API_KEY:PASSWORD@SHOP_NAME.myshopify.com" API_VERSION=2021-04

## Specifications

- `shopify_api` version: 9.4.1
- `activeresource` version: N/A
- Shopify API version used: 2021-04

**Comment by andyw8** [comment]
Can you share the output of `bundle exec rake --tasks`

**Comment by pupasam** [comment]
Hi, thank you for your prompt response.

When I run that from my project folder, no response
![Screenshot 2021-04-15 130440](https://user-images.githubusercontent.com/67614355/114931539-36f78a80-9deb-11eb-9802-4d43d878855c.png)

**Comment by pupasam** [comment]
Also no response when I run `rake shopify_api:graphql:dump`
