### ISSUE TITLE
Missing site URI

### ISSUE THREAD

**Issue by manuelmeurer** [Shopify/shopify_api#96]
I'm trying to access the current `ShopifyAPI::Shop` directly after a user has logged in:

``` ruby
class SessionsController < ApplicationController
  def show
    response = request.env['omniauth.auth']
    if response.present?
      auth_token = response['credentials']['token']
      session[:shopify] = ShopifyAPI::Session.new(params[:shop], auth_token)

      # This is where the error happens:
      Rails.logger.debug ShopifyAPI::Shop.current

      redirect_to root_path, notice: 'Successfully logged in.'
    else
      flash[:error] = 'Could not log in to Shopify shop.'
      redirect_to action: 'new'
    end
  end
end
```

Which raises the following error:

```
ArgumentError - Missing site URI:
  activeresource (4.0.0) lib/active_resource/connection.rb:35:in `initialize'
  activeresource (4.0.0) lib/active_resource/base.rb:590:in `connection'
  activeresource (4.0.0) lib/active_resource/base.rb:599:in `connection'
  activeresource (4.0.0) lib/active_resource/base.rb:982:in `find_one'
  activeresource (4.0.0) lib/active_resource/base.rb:876:in `find'
  shopify_api (3.1.8) lib/shopify_api/resources/shop.rb:6:in `current'
  app/controllers/sessions_controller.rb:9:in `show'
```

**Comment by Dragas** [comment]
You'd assume that it would be called by default when you call `ShopifyAPI::Session.new`
